permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: rdiscount

# 作者信息
author: 
  name: 渊祭
  email: kellywang.ok@gmail.com
  link: http://kreja.github.io/
  weibo: http://weibo.com/blusblue
  github: https://github.com/Kreja

# 站点信息
title: 渊祭
description: 渊祭的博客
url: http://kreja.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico

# google analytics 设置
ga:
  id: UA-52933845-1
  url: kreja.github.io

# disqus 设置
disqus:
  shortname: kreja

# 主题设置，自动激活某个标签
active: tags

# 首页除了最新文章外显示分类
cates: 
  - HTML

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
